[package]
name = "slimetools"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"   # 错误处理
rand = "0.8"     # 随机数生成（测试用）
num_cpus = "1.16"  # 获取 CPU 核心数（并行搜索用）

[profile.release]
lto = true          # 链接时优化
codegen-units = 1   # 单代码生成单元，提升优化
panic = "abort"     # 省略 panic 展开